name: build-docusaurus

on:
  pull_request:
    branches: main
    paths:
    - 'samples/**'
    - 'test-docusaurus-1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd test-docusaurus-1
          npm install 
          npm run build