name: deploy-docusaurus

on:
  push:
    branches: main
    paths:
    - 'samples/**'
    - 'test-docusaurus-1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          cd test-docusaurus-1
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: test-docusaurus-1/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}